---
  - name: Download Prometheus in CetOS
    get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v2.33.0/prometheus-2.33.0.linux-amd64.tar.gz"
      dest: /tmp/prometheus.tar.gz
    when: ansible_distribution == "CentOS"

  - name: Extract Prometheus in CentOS
    unarchive:
      src: /tmp/prometheus.tar.gz
      dest: /opt/
      remote_src: yes
      creates: /opt/prometheus-2.33.0
    when: ansible_distribution == "CentOS"

